### ISSUE TITLE
Chromeが起動できません

### ISSUE THREAD

**Issue by ts-ts** [stuncloud/UwscWebDriver#20]
環境を構築して、driver = WebDriver.Chrome()でchromeを起動しようとしましたが、エラーで起動できません
解決方法が分かれば、教えていただけないでしょうか
よろしくお願いいたします

```
call UwscWebDriver

try
	driver = WebDriver.Chrome() 
except
	print WebDriver.GetError()
endtry
```

[Print内容]
Number      :-2146697208
Source      :msxml3.dll
Description :指定されたリソースのダウンロードは失敗しました。
Text        :

[コマンドプロンプト]
Starting ChromeDriver 100.0.4896.60 (6a5d10861ce8de5fce22564658033b43cb7de047-re
fs/branch-heads/4896@{#875}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggest
ions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1648869085.164][SEVERE]: Cannot handle request with protocol: HTTP/1.0

[UWSCのエラーメッセージ]
COM_Error：例外が発生しました。
D:\Tools\UWSC_Script\UwscWebDriver.uws: 146行日: result = CodeObject.WebDriver.Start(uri, capabilities, debug)

**Comment by stuncloud** [comment]
UwscWebDriverのバージョンも教えて下さい

**Comment by ts-ts** [comment]
0.8.7です。

**Comment by stuncloud** [comment]
ありがとうございます
UwscWebDriver.uwsの1259行目

https://github.com/stuncloud/UwscWebDriver/blob/5afc6a419cae5d12bb9e0affacb4e38007643613/UwscWebDriver.uws#L1258-L1277

にある `Msxml2.XMLHTTP` を `Msxml2.XMLHTTP.6.0` と書き換えて改善するかどうか確認をお願いします

**Comment by ts-ts** [comment]
ありがとうございます
起動しませんでした

[Print内容]
Number      :-2146697208
Source      :msxml6.dll
Description :指定されたリソースのダウンロードは失敗しました。
Text        :

**Comment by stuncloud** [comment]
`WinHttp.WinHttpRequest.5.1`
だとどうでしょうか、こちらだとデフォルトでHTTP1.1を使うようなので

**Comment by ts-ts** [comment]
コマンドプロンプトは以下のような表示になり、無事起動しました
ありがとうございました

[コマンドプロンプト]
Starting ChromeDriver 100.0.4896.60 (6a5d10861ce8de5fce22564658033b43cb7de047-re
fs/branch-heads/4896@{#875}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggest
ions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:49836/devtools/browser/dad23eea-c5dc-4c91-a
632-4a44476e0ec3

**Comment by stuncloud** [comment]
このようなケースに備えて何かしらの対応を次のに入れます

**Comment by ts-ts** [comment]
対応、助かります
本当にありがとうございました

**Comment by stuncloud** [comment]
対応後にこちらでクローズします

**Comment by ts-ts** [comment]
失礼いたしました
承知しました

**Comment by stuncloud** [comment]
0.8.8で対応しました
`WinHttp.WinHttpRequest.5.1` を初期値にしました
