### ISSUE TITLE
driver.Navigate、driver.GetSession()のエラー

### ISSUE THREAD

**Issue by ts-ts** [stuncloud/UwscWebDriver#22]
## バグの概要

call UwscWebDriver
driver = WebDriver.Chrome(9515)
driver.Navigate("https://github.com/stuncloud/UwscWebDriver")

call UwscWebDriver
driver = WebDriver.Chrome(9515)
writeini("WebDriver", "session", driver.GetSession())

いずれも COM_Error: Could not convert variant of type (Null into type (Dispatch) でエラーをはくようになりました

## 実行環境

- UwscWebDriverバージョン
    - 0.8.9
- ブラウザ 
    - [x] Google Chrome
        - 102.0.5005.63（Official Build） （64 ビット)
    - [ ] Microsoft Edge
        - 0.0.0
    - [ ] Mozilla Firefox
        - 0.0.0
- webdriverバージョン
    - 102.0.5005.61
- OS
    - [ ] Windows 11
    - [ ] Windows 10
    - [ ] Windows 8.1
    - [x] Windows 7
    

## 補足
Chrome本体がアップデートされる前までは問題なく動作していました

**Comment by ts-ts** [comment]
すいません。
PCを再起動したら、いつものように動作するようになりました。
今後はあせって投稿しないように、気をつけます...

**Comment by stuncloud** [comment]
後ほど確認します

変数`driver`が`NULL`になってしまっているようですね
webdriverの仕様が変わって必要な値が取れなくなったのかもしれません

**Comment by stuncloud** [comment]
> PCを再起動したら、いつものように動作するようになりました。
あ、そうでしたかよかったです
でもなにが起きてたんでしょうね？なにか対策ができるならしたほうがいいのかな…？

**Comment by stuncloud** [comment]
#23 で警告を出すようにしました

**Comment by ts-ts** [comment]
より使いやすいアップデート、ありがとうございました。
