### ISSUE TITLE
Clearにより文字入力欄がクリアされません

### ISSUE THREAD

**Issue by Akki01234** [stuncloud/UwscWebDriver#24]
## 質問

text及びtextareaへ文字列を入力するにあたり、既に入力されている文字列があるため
clear()を実行するのですが、文字列がクリアされず、SeValue()により文字列が追記されてしまいます。

よろしくお願いします。

## コード例
```php
// 質問に関するコードがある場合ここに記述してください
driver.FindElement("input[name=mailSubject]").Clear()
driver.FindElement("input[name=mailSubject]").SetValue(subject)
driver.FindElement("textarea[name=mailBody]").Clear()
driver.FindElement("textarea[name=mailBody]").SetValue(message)

```

## 実行環境
- UwscWebDriverバージョン
    - 0.8.9
- ブラウザ 
    - [x] Google Chrome
        - 100.0.4896.127
- webdriverバージョン
    - 100.0.4896.60
- OS
    - [x] Windows 10

**Comment by stuncloud** [comment]
https://stackoverflow.com/a/50691625

によると`form`の`autocomplete`属性が無効だと`/clear`が効かないようです
暫定対策ですが、以下が(おそらく)有効です

```stylus
mailSubject = driver.FindElement("input[name=mailSubject]")
// mailSubject.Clear()
mailSubject.ExecuteScript("$0.value = '';")
mailSubject.SetValue(subject)
```

**Comment by Akki01234** [comment]
ありがとうございます！
試してみたところ、①は既存の文字が削除され、新たな文字のみ記入されましたが、
②は既存の文字の後ろに追加されました。

①
mailBody = driver.FindElement("textarea[name=mailBody]")
mailBody.ExecuteScript("$0.value = '';")
mailBody.SetValue(message)
②
mailSubject = driver.FindElement("input[name=mailSubject]")
mailSubject.ExecuteScript("$0.value = '';")
mailSubject.SetValue(subject)

頂いたのをヒントに色々試してみたいと思いますが、何かわかりましたらご教示ください。

**Comment by stuncloud** [comment]
> によると`form`の`autocomplete`属性が無効だと`/clear`が効かないようです

無効(`off`)ではなく有効(`on`)の誤りでした

> 頂いたのをヒントに色々試してみたいと思いますが、何かわかりましたらご教示ください。

こちらでは再現できませんでした (Clearが正常に動作する)  
そちらで実行されたコード以外の情報がないのでこちらではこれ以上の調査ができません  
こちらでの調査を希望するのであれば、不足している実行環境の情報をください  
こちらで現象が再現できない限り調査は不可能です

- form部分のHTMLソース
- 「既存の文字」がどのように入力されていたのか
- 可能ならサイトのURL

等ですかね

**Comment by Akki01234** [comment]
ありがとうございます。
下記にお知らせします。よろしくお願いします。

●HTMLソース
①クリアされる
```php
<textarea class="MultilineTextInput MailBodyInput need-validation validity-valid" name="mailBody">
「既存の文字」
</textarea>
```
②クリアされない
```php
<input class="TextInput need-validation validity-valid has-right-control-type-clear right-control-visible" type="text" name="mailSubject" placeholder="" value="既存の文字">
```
●文字列の追加のされ方
　①「既存の文字」がクリアされ、message が追加
　②「既存の文字」に続けて、subject が追加

●サイトのURL
　IDでログインするサービスサイトのため展開は困難

**Comment by stuncloud** [comment]
> ●HTMLソース
> ①クリアされる
> ```php
> <textarea class="MultilineTextInput MailBodyInput need-validation validity-valid" name="mailBody">
> 「既存の文字」
> </textarea>
> ```
> ②クリアされない
> ```php
> <input class="TextInput need-validation validity-valid has-right-control-type-clear right-control-visible" type="text" name="mailSubject" placeholder="" value="既存の文字">
> ```

`autocomplete`についてはお伝えしていたのでせめて`form`以下が見たい、ということでform部分の、と書いておいたのですが伝わらないものですね
部分的なソースを見てもわかることは少なさそうなので、この件についての追加の情報は不要です

> ●文字列の追加のされ方
> 　①「既存の文字」がクリアされ、message が追加
> 　②「既存の文字」に続けて、subject が追加

それはSetValueした際の動作ですよね、それは既に把握していますし聞いていません
そうではなく「既存の文字」そのものが何によってどのタイミングでどのように入力されていたか？を聞いていました
しかしそれを調べていただくのも難しいと思われるのでこれについても追加の情報は不要です

----

申し訳ないのですが今のところ僕が本件に割けるリソースがさほどない状態なので、情報不足のまま調査を丸投げということであれば解決できるのはいつになるかわかりません
なので可能であれば現象を再現可能なページを用意していただきたいのです

- 他のサイトで再現可能であればそのURL
- (可能であれば)再現可能ページを作成し、いずこかで公開あるいは作成したHTMLファイル等を添付

などこちらから容易にアクセスできる手段であればなんでも構いません
よろしくお願いします

**Comment by Akki01234** [comment]
やりとりに慣れておらず失礼しました。
本番サイトはIPアドレスでアクセス制限されているため、
該当HTMLを抜き出して下記サイトに設置してみました。
こちらでご覧いただけますでしょうか。

http://www1.odn.ne.jp/~aqp31020/sample.html

お手数をおかけしますが、よろしくお願いします。

**Comment by Akki01234** [comment]
>本番サイトはIPアドレスでアクセス制限されているため、
該当HTMLを抜き出して下記サイトに設置してみました。
こちらでご覧いただけますでしょうか。
http://www1.odn.ne.jp/~aqp31020/sample.html

すいません、自己レスですが、こちらのテストサイトで試したところ、正常にクリアされておりました
（事象が再現できない）。
再現確認をして頂く方法をもう少し模索してみます。

**Comment by Akki01234** [comment]
再度自己レスです。
色々試してみたところ、値を書き込む前に該当エリアをクリックしておくと
期待通りの動作（クリアした後に値を書き込む）をしてくれました。
理由は不明ですが解決しました。色々お手数をおかけしましたが、ありがとうございました。

```php
mailSubject = driver.FindElement("input[name=mailSubject]")
mailSubject.Click()
mailSubject.ExecuteScript("$0.value = '';")
mailSubject.SetValue(subject)

**Comment by stuncloud** [comment]
wikiに [Clearが効かない場合の対処法](https://github.com/stuncloud/UwscWebDriver/wiki/Clear%E3%81%8C%E5%8A%B9%E3%81%8B%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AE%E5%AF%BE%E5%87%A6%E6%B3%95) を追加しました
このようなケースでの対処法としてClick()を使う方法などを記載しました
調査及びご報告ありがとうございました
