### ISSUE TITLE
GetText実行時の挙動

### ISSUE THREAD

**Issue by ts-ts** [stuncloud/UwscWebDriver#26]
エレメント内の文字列を取得しようとして、そのタグが存在しない場合(text=""となる場合)
②は待ち時間がほとんどないのですが、①は待ち時間が生じます
GetAttribute()も同じような挙動です
これは仕様でしょうか？

※セレクターは例です
①driver = WebDriver.Chrome(9515)
driver.Navigate("hogehoge")
text = driver.FindElement( By.Tag("div") + By.Attribute("data-area", "prizeName") ).GetText()

②driver = WebDriver.Chrome(9515)
driver.Navigate("hogehoge")
page_source = driver.GetSource()
text = BetweenStr(page_source, "<div data-area=<#DBL>prizeName<#DBL> class=<#DBL>prizeName<#DBL>>", "</div>")

## 実行環境
- UwscWebDriverバージョン
    - 0.9.2

- ブラウザ 
    - Google Chrome バージョン: 103.0.5060.134（Official Build） （64 ビット）

- webdriverバージョン
    - 103.0.5060.134

- OS
    - Windows 7

**Comment by stuncloud** [comment]
以下がわからないので教えて下さい

- 待ち時間とは具体的にどのくらいの長さですか？これは実行の度に変動しますか？それとも毎回同じくらいでしょうか？
- ①と②はともにtextに空文字(`""`)が返るということですか？
- タグが存在しない場合、とありますがdivタグは存在していて、そのなかにテキスト(`textContent`)がないという意味ですか？
- GetAttribute()も同じような挙動、というのは具体的にどのようなケースですか？ 
    - 存在しないアトリビュートを指定？
    - アトリビュートは存在するが値がない(空文字)の場合？

**Comment by stuncloud** [comment]
- divにtextContentが
    - ある場合
    - ない場合
- divのattributeに値が
    - ある場合
    - ない場合
- divにattributeがない場合

で動作を見てみました  
検証用コードは以下です

```html
<div>
    <div id="hastext" foo="ふがふが">ほげほげ</div>
    <div id="notext" foo=""></div>
    <div id="noattr"></div>
</div>
```

```stylus
def_dll GetTickCount():dword:kernel32.dll

hastext = driver.FindElement("#hastext")
start = GetTickCount()
text = hastext.GetText()
end = GetTickCount()
print "hastext.GetText(): " + (end-start)

start = GetTickCount()
text = hastext.GETATTRIBUTE("foo")
end = GetTickCount()
print "hastext.GetAttribute(): " + (end-start)

notext = driver.FindElement("#notext")
start = GetTickCount()
text = notext.GetText()
end = GetTickCount()
print "notext.GetText(): " + (end-start)

start = GetTickCount()
text = notext.GetAttribute("foo")
end = GetTickCount()
print "notext.GetAttribute(): " + (end-start)

noattr = driver.FindElement("#noattr")
start = GetTickCount()
text = noattr.GetText()
end = GetTickCount()
print "noattr.GetText(): " + (end-start)

start = GetTickCount()
text = noattr.GetAttribute("foo")
end = GetTickCount()
print "noattr.GetAttribute(): " + (end-start)
```

結果、いずれのケースでも16ミリ秒以内には処理が完了しており待ち時間があるとは感じられませんでした
検証に用いたChrome及びchromedriverのバージョンは`103.0.5060.134`です

**Comment by stuncloud** [comment]
以下をください

- 現象を再現させられるコード
- その際に開くページのhtmlファイル

**Comment by ts-ts** [comment]
毎回、迅速かつ丁寧な回答ありがとうございます。
現象を再現させられるコードは以下のとおりです。
画面中央のボタンがログイン前とログイン後で変わります・

[UWSCコード①]
//GetText()で指定したセレクターが存在しないため、テキストが取得できないケース：終了まで約10秒
WebDriver.HideCmd()
driver = WebDriver.Chrome(9515)
driver.Navigate("https://toku.yahoo.co.jp/tpointevery/lot")
Try
	button_text = driver.FindElement( By.Id("btnLot") ).GetText()
Except
	button_text = "なし"
EndTry
	Print button_text

[UWSCコード②]
//BetweenStr()でテキストが取得できないケース：終了まで数秒
WebDriver.HideCmd()
driver = WebDriver.Chrome(9515)
driver.Navigate("https://toku.yahoo.co.jp/tpointevery/lot")
page_lottery_source = driver.GetSource()
Try
	button_text = BetweenStr(page_lottery_source, "<button id=<#DBL>btnLot<#DBL> type=<#DBL>submit<#DBL> class=<#DBL>baseBtn btnTypeKujiOn<#DBL> data-ylk=<#DBL>slk:lotbtn;pos:0<#DBL>>", "</button>")
Except
	button_text = "なし"
EndTry
	Print button_text

[UWSCコード③]
//GetText()でテキストが取得できるケース：終了まで数秒
WebDriver.HideCmd()
driver = WebDriver.Chrome(9515)
driver.Navigate("https://toku.yahoo.co.jp/tpointevery/lot")
Try
	button_text = driver.FindElement( By.Tag("div") + By.Attribute("data-area", "btnActionLogin") ).GetText()
Except
	button_text = "なし"
EndTry
	Print button_text

[UWSCコード④]
//BetweenStr()でテキストが取得できるケース
WebDriver.HideCmd()
driver = WebDriver.Chrome(9515)
driver.Navigate("https://toku.yahoo.co.jp/tpointevery/lot")
page_lottery_source = driver.GetSource()
Try
	button_text = BetweenStr(page_lottery_source, "<p class=<#DBL>btnBox_loginNotes<#DBL>>", "</p>")
Except
	button_text = "なし"
EndTry
	Print button_text

[ページのソースの抜粋]
・ログインボタン表示
 <div data-area="btnActionLogin" class="btnBox" id="btn">
                            <a href="https://login.yahoo.co.jp/config/login?.src=kuji&amp;card_cushion_skip=1&amp;.done=https://toku.yahoo.co.jp/tpointevery/lot" class="baseBtn btnTypeLogin" data-ylk="slk:login;pos:0">ログインする</a>
                            <p class="btnBox_loginNotes">Yahoo! JAPAN IDを新規取得されると参加可能になるまでにお時間をいただく場合があります</p>
                        </div>

・今日のくじを引く ボタン表示(ログイン後)
<div id="btn">
                                    <button id="btnLot" type="submit" class="baseBtn btnTypeKujiOn" data-ylk="slk:lotbtn;pos:0">今日のくじを引く</button>
                                </div>

**Comment by stuncloud** [comment]
tryで囲ってるということは該当エレメントが見つからない場合なんですね？
(できれば先にこちらからの質問への回答が欲しかったです)
その場合待ち時間があるのは仕様です

FindElement系はエレメントが見つかるまで最大10秒待つ、という仕様があります
これは動的に生成されるエレメントを補足するために有用です

この時間は変更することが可能です
```stylus
driver.SetImplicitWait(500) // 待ち時間をミリ秒で指定、初期値は10000 (10秒)
```
一度変更すれば以後はその待ち時間が適用されます
このメソッドについてはドキュメント未記載なので記載しておきます

**Comment by ts-ts** [comment]
回答に不備があり申し訳ございませんでした
おっしゃるとおり該当エレメントが見つからない場合です
説明していただいた内容でよく分かりました
ありがとうございました

追加で教えてほしいのですが、
IEの場合はIE.Navigateのあとに、Busywaitを適宜入れて読み込み完了を確認して次のコマンドに移るといったコードが必要でしたが、
Seleniumの場合はBusywait的なものはdriver.Navigate()に内包されているとの理解でよろしいでしょうか？

**Comment by stuncloud** [comment]
Seleniumについてはわかりません
UwscWebDriverについては、ある程度はwebdriver側で待ってくれるはずです
確実に完了を待ちたいのであれば
```stylus
driver.Navigate(url)
// selectorが示すエレメントが見つかるまで待つ
while driver.FindElement( selector ) = NULL
    sleep(0.1)
wend
```
というように記述するのが一番簡単な方法です
(ここでのselectorは画面描画が完了したときに表示されているエレメントのいずれかを指定します)

**Comment by ts-ts** [comment]
UwscWebDriverでの仕様、理解できました
本当にありがとうございました

**Comment by stuncloud** [comment]
本件について他になにもなければクローズしておいてください
