### ISSUE TITLE
Frameで分離されたサイトの操作

### ISSUE THREAD

**Issue by Akki01234** [stuncloud/UwscWebDriver#27]
## 質問

Frameで分離されたサイトを操作する方法を教えてください

## コード例

frame src="MenuBfAction.do" name="index_doko"

## 実行環境

- UwscWebDriverバージョン
    - 0.8.9
- ブラウザ 
    - [x] Google Chrome
        - 102.0.5005.115
    - [ ] Microsoft Edge
        - 0.0.0
    - [ ] Mozilla Firefox
        - 0.0.0
- webdriverバージョン
    - 102.0.5005.61
- OS
    - [ ] Windows 11
    - [x] Windows 10
    - [ ] Windows 8.1
    - [ ] Windows 7
- 操作対象の情報
    - URL:

**Comment by stuncloud** [comment]
## 操作フレーム切り替え (試験的機能)

一応[SwitchFrame](https://github.com/stuncloud/UwscWebDriver/wiki/driver%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88#switchframe)というメソッドがあり、これでフレーム内に操作対象を切り替えられる…はずなのですが、現状うまくフレームを掴めない事があるようです (とりあえずで実装していて検証も不十分な実験的機能という位置づけです)
```stylus
driver.SwitchFrame(0) // 1つ目のフレームに移動
driver.SwitchFrame(1) // 2つ目のフレームに移動
driver.SwitchFrame(-1) // 親フレームに移動
```

## 別解

特にフレーム越しで操作する必要がないのであれば (そして多くの場合ないと思うんですが)、フレーム内で表示されているページのURLを直接別のタブで開き、そちらを操作するという手があります  

```html
<frameset>
    <frame src="frame1.html" name="frame1">
    <frame src="frame2.html" name="frame2">
</frameset>
```

```stylus
frame1 = driver.findElement("frame[name=<#DBL>frame1<#DBL>]") // フレームを取得

current = driver.GetCurrentWindowHandle()
driver.navigate(frame1.src, "frame1") // frame1のURLを別タブで開く
driver.SwitchWindow("frame1") // 別タブに操作対象を移す

// 別タブ上で操作を行う

driver.SwitchWindow(current) // 元のタブに戻る
```

**Comment by Akki01234** [comment]
ありがとうございます。
SwitchFrame、別解共に試したのですが、共にNGでした

+ SwitchFrame
　後続の処理でエラー
+ 別解
　Frame部分で「Error 404--Not Found」

別解は引き続き確認しますが、SwitchFrameは後続処理の記述が間違っているかもしれないので、
こちらの記述方法も合わせて教えて頂けますと助かります。

下記リンクをクリック

    <a href="SearchReferenceBfAction.do?RK_COMPULSIVE=RK_COMPULSIVE&amp;RK_STATUS_KBN_FLG=0&amp;refStatus=status0002" target="body_doko" onclick="return click_event('linkDR05', true);">雛形保存</a>

よろしくお願いします。

**Comment by stuncloud** [comment]
記述方法というのはセレクタがわからないということですか？
この場合は `a[target="body_doko"]` になると思います
クリックは `Click()`です

**Comment by stuncloud** [comment]
ちなみにframeへの正式対応をする予定はありません
今となってはframe自体が非推奨であり、今さらframeを使っていることのほうがおかしいと考えているからです

とはいえ僕にこれを実装する意思がないというだけで、プルリクは歓迎しますよ！

**Comment by Akki01234** [comment]
> 記述方法というのはセレクタがわからないということですか？
> この場合は `a[target="body_doko"]` になると思います
> クリックは `Click()`です

ありがとうございます。が、うまく行きませんでした。
SwitchFrameが起因してるかも知れないので、
もう少し試してみます。

**Comment by Akki01234** [comment]
本件ですが、知人がuwsc webdriverのソースをみて下記修正をして頂く事で
一旦解決しました。

```
WebDriver.prototype.SwitchFrame = function(id) {
    var api = '/frame';
    var body = {};
    if (id < 0) {
        api += '/parent'
    } else {
        //body["id"] = id || null;
        body["id"] = id;
    }
    var r = this.request.Post(api, body);
    //return JSON.stringify(r);
    return r != null && r.value == null
};
```

**Comment by Akki01234** [comment]
本件ですが、知人がuwsc webdriverのソースをみて下記修正をして頂く事で
一旦解決しました。

```
WebDriver.prototype.SwitchFrame = function(id) {
    var api = '/frame';
    var body = {};
    if (id < 0) {
        api += '/parent'
    } else {
        //body["id"] = id || null;
        body["id"] = id;
    }
    var r = this.request.Post(api, body);
    //return JSON.stringify(r);
    return r != null && r.value == null
};
```

**Comment by stuncloud** [comment]
ああなるほど、これだと引数のidに `0` を渡すと `null` になってしまってましたね
ひどいバグを仕込んでしまってました、申し訳ない
修正版をリリースします
