### ISSUE TITLE
XPath内で変数を使用したい

### ISSUE THREAD

**Issue by Akki01234** [stuncloud/UwscWebDriver#28]
## 質問
XPath内で変数をするにはどのように記述すれば良いでしょうか？
いくつか試したのですが、どれも成功しませんでした。

## コード例

成功するコード
```
driver.FindElementByXPath("//a[contains(text(),'FORM000000038850')]").Click() 
```

失敗するコード①
```
var2 = "FORM000000038850`
driver.FindElementByXPath("//a[contains(text(),var2)]").Click() 
```

失敗するコード②
```
var2 = "FORM000000038850"
var2 = "'" + var2 + "'"
driver.FindElementByXPath("//a[contains(text(),var2)]").Click()
```

## 実行環境

- UwscWebDriverバージョン
    - 0.8.9
- ブラウザ 
    - [X] Google Chrome
        - 0\102.0.5005.115
    - [ ] Microsoft Edge
        - 0.0.0
    - [ ] Mozilla Firefox
        - 0.0.0
- webdriverバージョン
    - 0.0.0
- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] Windows 8.1
    - [ ] Windows 7
- 操作対象の情報
    - URL:

**Comment by stuncloud** [comment]
申し訳ないのですが、できればUwscWebDriverに **直接関係のない質問はご遠慮いただきたい** です

なのでヒントだけ

## ヒント①

失敗するコードのいずれも変数 `var2` は値が代入されただけで **使われていない** です

## ヒント②

UWSCの文字列結合は `+` 演算子を使います

```stylus
変数 = "bar"
print "foo" + 変数 + "baz" // foobarbaz
```

失敗するコード②に
> var2 = "'" + var2 + "'"

という記述があるのでおそらくそれは理解されているものと思います  
でもそこまでわかってればもう答えはわかりますよね…？

**Comment by Akki01234** [comment]
解決しました。ありがとうございました
