### ISSUE TITLE
Webdriver.Chrome()が起動しない

### ISSUE THREAD

**Issue by Akki01234** [stuncloud/UwscWebDriver#29]
## 質問

Webdriver.Chrome()を実行すると下記エラーがコマンドプロンプトで表示され、その後、
「Webdriverが起動していません」というポップアップが表示されます。

chromedriver.exe"は、内部コマンドまたは外部コマンド、操作可能なプログラムまたはバッチファイルとして認識されていません

UWSCの実行ファイルなど全てUNC（Windows共有フォルダ）に配置しているので、それが問題なのでしょうか。

よろしくお願いします。

## 実行環境
- UwscWebDriverバージョン
    - 0.8.9
- ブラウザ 
    - [X] Google Chrome
        - 102.0.5005.115
    - [ ] Microsoft Edge
        - 0.0.0
    - [ ] Mozilla Firefox
        - 0.0.0
- webdriverバージョン
    - 0.0.0
- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] Windows 8.1
    - [ ] Windows 7
- 操作対象の情報
    - URL:

**Comment by stuncloud** [comment]
> chromedriver.exe"は、内部コマンドまたは外部コマンド、操作可能なプログラムまたはバッチファイルとして認識されていません

これは `chromedriver.exe` が実行するスクリプトと同じパスに存在しない、または `%PATH%` 上に存在しない場合に表示されます
実行スクリプトがある場所がカレントディレクトリになり、PATHを通していない場合はそこにあるchromedriverを実行することになります
共有フォルダ上ということでカレントディレクトリが予期せぬものになっているのかもしれません
以下はどの様になっていますか？

- 実行するスクリプトの置き場所 (パス)
- chromedriverの置き場所 (パス)
- uwsc.exeの置き場所 (パス)
- `GET_CUR_DIR`の値
- 実行方法
    - `.uws`ファイルがuwsc.exeに関連付けされているか
    - explorerからの実行か、コンソール(powershell、cmd)
    - UNCパスかネットワークドライブか

**Comment by stuncloud** [comment]
ローカルにコピーしても問題ないのであればローカルに置いて実行してください

**Comment by Akki01234** [comment]
お世話になります。ご回答ありがとうございます。

当方の環境は下記となります。

+ 実行するスクリプトの置き場所 (パス)
`\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\データ提供依頼\Sub`　①
+ chromedriverの置き場所 (パス)
`\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\データ提供依頼\Sub`
+ uwsc.exeの置き場所 (パス)
`\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\Tools`　②
+ `GET_CUR_DIR`の値
`\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\データ提供依頼\Sub`

+ 実行方法
  コンソール上で下記が記載されているバッチファイルを実行
```
set svrdir=\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\データ提供依頼　③
set uwsc=%svrdir%\..\Tools\uwsc.exe
%uwsc% %svrdir%\Sub\Summit-chrome.uws %sid% %spw%
```
念のため、上記①②③すべてに'chromedriver.exe'を置いてみましたが、動作変わらずでした。
ちなみにこれをごっそりローカルにコピーすると問題なく動作します。そのため共有フォルダに
置いてあるのが原因なのかと思うのですが、実務上共有フォルダに置きたいと考えています。

ちなみに他サイトに載っていた下記も試しましたが、executable_pathが定義されていないエラーがでました。
`driver = webdriver.Chrome(executable_path="W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver")`

上記以外でchromedriverの場所を明示的に示す方法ってありますでしょうか？

**Comment by stuncloud** [comment]
> ちなみに他サイトに載っていた下記も試しましたが、executable_pathが定義されていないエラーがでました。
> driver = webdriver.Chrome(executable_path="W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver")

`executable_path=`の部分が不要です
`driver = webdriver.Chrome("W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver.exe")`
ですね

ただ、どのみち`doscmd`を使っているので失敗するかもしれません
どうにかならないか調べてみます

**Comment by Akki01234** [comment]
お世話になります。
下記に修正しましたところ、エラーが出ましたのでお知らせします。よろしくお願いします。

＜修正箇所＞
```
//driver = WebDriver.Chrome()
driver = Webdriver.Chrome("W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver.exe")
```

＜エラー＞
```
COM_Error：例外が発生しました。
uwswebdriver.uws:742行目：RESULT = Q.Count
```

＜該当箇所＞

    function FindListeningPort(port)
        if kindofos() > 24 then
            dim service = locator.ConnectServer(".", "Root\StandardCimv2")
            dim q = service.ExecQuery("select LocalPort from MSFT_NetTCPConnection where LocalPort = " + port + " and state = 2")
            result = q.Count
        else
            if betweenstr(doscmd("netstat -anp tcp"), ":" + port, "LISTENING") <> "" then
               result = 1
            else
               result = 0
            endif
        endif
    fend

**Comment by stuncloud** [comment]
UNCパス上でdoscmdを実行するとカレントディレクトリが`%windir%`か`%SystemRoot%`、つまり多くの場合`C:\Windows`になるので回避策としては

- 環境変数`%PATH%`に`\\bbwcfs.local\share97\DATA16\SharePrj\cl-manual\日次データ\データ提供依頼\Sub`を一時的に加える
- `C:\Windows`に`chromedriver.exe`を置く

などが考えられます

UwscWebDriver側での対処法として

1. webdriverの起動を試みる
2. 失敗した場合
    - webdriverのパスが相対パスだったら絶対パスにして再実行

とする処理を加えてみようと思います
(`doscmd`から実行する際に絶対パス指定であればUNCパスも有効であるため)
この修正を含むリリースは早ければ今日中に行います

**Comment by stuncloud** [comment]
> 下記に修正しましたところ、エラーが出ましたのでお知らせします。よろしくお願いします。
すいません、先のコメントの間違いに気づいて編集したのですが少し遅かったようですね
webdriverのパスを渡すには`Start()`を使う必要があります

```diff
    //driver = WebDriver.Chrome()
-   driver = Webdriver.Chrome("W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver.exe")
+   driver = Webdriver.Start("W:\Desktop\uwsc5302\データ提供依頼\Sub\chromedriver.exe")
```

**Comment by stuncloud** [comment]
0.9.4をリリースしました

```stylus
Webdriver.Chrome()
```

でも成功するようになったと思います

**Comment by Akki01234** [comment]
ありがとうございます。
取り急ぎ、コードは変更せずに0.9.4に入れ替えて実行させたところ、
下記エラーが出るようになりました。

```
変数：&#39；が定義されていません
CONST $0 = ARGUMENTS[$#39; + I + $#39;]
```

`driver = WebDriver.Chrome()`は変更していません

ご確認お願いします。

**Comment by stuncloud** [comment]
こちらでは再現しません

> 0.9.4に入れ替えて

入れ替えはどのようにしましたか？
ReleaseページのAssetsからダウンロードすれば問題ないはずですが、ファイルの差し替え方法を教えてください

**Comment by Akki01234** [comment]
>入れ替えはどのようにしましたか？
>ReleaseページのAssetsからダウンロードすれば問題ないはずですが、ファイルの差し替え方法を教えてください

やり方が適切でなかったようです。ご指示のやり方でDLして既存ファイルと差し替えたら、エラーは出ませんでした。

また、先の%PATH%に共有フォルダを一時的に加えることでwebdriverが起動しました。
ありがとうございました。
