### ISSUE TITLE
FireFoxで自分のプロファイルを使う

### ISSUE THREAD

**Issue by Yam-01** [stuncloud/UwscWebDriver#30]
## 質問
FireFoxで自分のプロファイルを使いたい

## コード例

call "UwscWebDriver.uws"

opt = WebDriver.Option("Firefox")
opt.args.add("-p default-releaser")

driver = WebDriver.Firefox(9515, opt)
driver.Navigate("https://www.yahoo.co.jp")

#### UwscWebDriverバージョン

最新

#### webdriverバージョン

最新

## 補足

Firefoxは起動できて、Yahooページも開くのですが、ログアウトしています。

因みに、UWSCから
Doscmd("<#DBL>C:\Program Files\Mozilla Firefox\firefox.exe<#DBL> -p default-release")
だと、希望通りログイン状態でページは開きます。

よろしくお願いします

**Comment by stuncloud** [comment]
コード例の方でプロファイル名が `default-releaser` になってますが、これをコマンド例にある `default-release` にしてもだめですか？

```stylus
opt.args.add("-p")
opt.args.add("default-releaser") // default-release ?
```

とした場合はどうでしょうか

**Comment by stuncloud** [comment]
`-p` ではなく `-profile` でプロファイルパスを指定すればうまくいくかもしれません
