### ISSUE TITLE
cssセレクタを指定せずとも柔軟にエレメントを探せるようにする

### ISSUE THREAD

**Issue by stuncloud** [stuncloud/UwscWebDriver#7]
http://www3.rocketbbs.com/601/bbs.cgi?id=siromasa&mode=pickup&no=711

>代わりにセレクタを使わない形でエレメントの指定がしやすくなるようなメソッドを実装できないか考えてみますね

**Comment by satocha** [comment]
xpathで指定できるといいなあとリクエストします。
python　find_element_by_xpath
c#　FindElement(By.Xpath("xpath"))
みたいな感じで。

**Comment by stuncloud** [comment]
https://w3c.github.io/webdriver/#xpath

**Comment by stuncloud** [comment]
@satocha 0.3.8で追加しました
Chrome、Edge、Firefoxで動作確認済みです

**Comment by satocha** [comment]
ありがとうございます

**Comment by stuncloud** [comment]
Byモジュールで直接cssを記述しなくてもよくなりました
